version: "3"
services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      HOST: 0.0.0.0
    volumes:
      - ../:/workspace
      - build:/workspace/build
      - node_modules:/workspace/node_modules
    command: sleep infinity

volumes:
  node_modules:
  build: