version: '3'
services:
  akgg:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - '3000:3000'
    environment:
      HOST: 0.0.0.0
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ../.devcontainer:/workspace/.devcontainer
      - ../.vscode:/workspace/.vscode
      - ../src:/workspace/src
      - ../web:/workspace/web
      - ../package.json:/workspace/package.json
      - ../tsconfig.json:/workspace/tsconfig.json
      - ../netlify.toml:/workspace/netlify.toml
      - ../README.md:/workspace/README.md
      - ../.git:/workspace/.git
      - ../.gitignore:/workspace/.gitignore
    command: sleep infinity
