name: Data

on:
  schedule:
    - cron:  '0 */6 * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST -d {} ${{ secrets.BUILD_HOOK }}
